server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-order-consumer   #匹配后提供服务的路由地址
          predicates:
            - Path=/order/feign/**   #断言,路径相匹配的进行路由
          #StripPrefix=1就代表截取路径的个数，这样配置后当请求/config/feign/get后端匹配到的请求路径，
          #就会变成http://localhost:8762/feign/get后端匹配到的请求路径
          filters:
            - StripPrefix=1
        - id: payment_routh2
          uri: lb://nacos-config-client

          predicates:
            - Path=/config/feign/**   #断言,路径相匹配的进行路由
        #StripPrefix=1就代表截取路径的个数，这样配置后当请求/config/feign/get后端匹配到的请求路径，
        #就会变成http://localhost:8762/feign/get后端匹配到的请求路径
          filters:
            - StripPrefix=1
