server:
  port: 80
spring:
  application:
    name: feign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #服务注册中心地址
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.stu.app.fegin.TestFeign2: debug